/*
 * Patient API
 * Patient API using swagger.io by Himesh Sharma
 *
 * OpenAPI spec version: 1.0.0
 * Contact: himesh.sharma2019@vitbhopal.ac.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
