/*
 * Patient API
 * Patient API using swagger.io by Himesh Sharma
 *
 * OpenAPI spec version: 1.0.0
 * Contact: himesh.sharma2019@vitbhopal.ac.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Patient
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-29T17:35:18.417435506Z[GMT]")
public class Patient {
  @SerializedName("PatientID")
  private Integer patientID = null;

  @SerializedName("PatientName")
  private String patientName = null;

  @SerializedName("PatientProblem")
  private String patientProblem = null;

  @SerializedName("Bill")
  private Integer bill = null;

  public Patient patientID(Integer patientID) {
    this.patientID = patientID;
    return this;
  }

   /**
   * Get patientID
   * @return patientID
  **/
  @Schema(example = "401", description = "")
  public Integer getPatientID() {
    return patientID;
  }

  public void setPatientID(Integer patientID) {
    this.patientID = patientID;
  }

  public Patient patientName(String patientName) {
    this.patientName = patientName;
    return this;
  }

   /**
   * Get patientName
   * @return patientName
  **/
  @Schema(example = "Yash", description = "")
  public String getPatientName() {
    return patientName;
  }

  public void setPatientName(String patientName) {
    this.patientName = patientName;
  }

  public Patient patientProblem(String patientProblem) {
    this.patientProblem = patientProblem;
    return this;
  }

   /**
   * Get patientProblem
   * @return patientProblem
  **/
  @Schema(example = "Cancer", description = "")
  public String getPatientProblem() {
    return patientProblem;
  }

  public void setPatientProblem(String patientProblem) {
    this.patientProblem = patientProblem;
  }

  public Patient bill(Integer bill) {
    this.bill = bill;
    return this;
  }

   /**
   * Get bill
   * @return bill
  **/
  @Schema(example = "5000000", description = "")
  public Integer getBill() {
    return bill;
  }

  public void setBill(Integer bill) {
    this.bill = bill;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Patient patient = (Patient) o;
    return Objects.equals(this.patientID, patient.patientID) &&
        Objects.equals(this.patientName, patient.patientName) &&
        Objects.equals(this.patientProblem, patient.patientProblem) &&
        Objects.equals(this.bill, patient.bill);
  }

  @Override
  public int hashCode() {
    return Objects.hash(patientID, patientName, patientProblem, bill);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Patient {\n");
    
    sb.append("    patientID: ").append(toIndentedString(patientID)).append("\n");
    sb.append("    patientName: ").append(toIndentedString(patientName)).append("\n");
    sb.append("    patientProblem: ").append(toIndentedString(patientProblem)).append("\n");
    sb.append("    bill: ").append(toIndentedString(bill)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
